### ISSUE TITLE
Online Editor

### ISSUE THREAD

**Issue by tronical** [sixtyfpsui/sixtyfps#37]
This ticket tracks the availability of support for a basic "online live editor" that allows editing `.60` markup code in a text field in a web browser and update a separate canvas preview, for example by pressing an "Update Preview" button or by updating automatically.

This could be integrated into our documentation and allow users to explore examples further by playing around with them.

**Comment by ogoffart** [comment]
Work in progress in https://sixtyfps.io/editor
(This is currently a single .hml file using the monaco editor)

What remains to be done is
 - [ ] Better styling so it looks somehow prettier
 - [ ] Error message with line number, and show it inline in the source
 - [ ] Button to compile instead of doing it on every keystroke.  We could keep a checkbox to enable the mode where we recompile on every keystroke
 - [ ] Combobox to switch to some default examples. Also ability to set the source code from the URL.
 - [ ] image support. (The compiler should be able to load image from an URL with wasm somehow)

 
Optional:
 - [ ] get the monaco editor from npm and have a build system like most web app do.

The source code is currently in the www repo:
https://github.com/sixtyfpsui/www/blob/master/editor/index.html but it should be maybe moved to this repository somwehere.

**Comment by ogoffart** [comment]
The code editor is now in the repository.  Closing this issue and track with sub issues
